# Example Shiny app. This file was automatically generated by crant.
library(shiny)

df <- read_diabetes()

ui <- fluidPage(titlePanel("Hello, data"))
server <- function(input, output) {}
shinyApp(ui=ui, server=server)

