# Example Shiny app. This file was automatically generated by crant.
# Run using shiny::runApp('$app')
library(shiny)

ui <- fluidPage(titlePanel("Hello, data"))
server <- function(input, output) {}
shinyApp(ui=ui, server=server)

