# Example Shiny app. This file was automatically generated by crant.
library(shiny)
library(devtools)
library(futile.logger)
setwd("..")
load_all()

df <- transform_diabetes(read_diabetes())

ui <- fluidPage(
  titlePanel("Glucose levels and insulin doses"),

  sidebarLayout(
    sidebarPanel(
      selectInput("patient_id", "Patient", unique(df$id))
    ),
    mainPanel(plotOutput("glucose_plot", height=800))
  )
)
server <- function(input, output) {
  output$glucose_plot <- renderPlot({
    flog.info("Rendering patient id: %s", input$patient_id)
    plot_glucose_and_insulin(df, input$patient_id)
  })
}
shinyApp(ui=ui, server=server)

